# base image elixer to start with
FROM elixir:1.5

# create app folder
RUN mkdir /app
COPY . /app
WORKDIR /app

# install hex package manager
RUN mix local.hex --force
RUN mix local.rebar --force

# install the latest phoenix 
RUN mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez --force
# install dependencies
RUN mix deps.get
# Compile the project
RUN mix do compile
# RUN chmod +x /app/entrypoint.sh
CMD ["/app/entrypoint.sh"]
# CMD mix phx.server