FROM node:10.12-alpine
RUN npm install -g yarn
WORKDIR /app/assets
COPY assets/package.json assets/*yarn* ./
RUN npm install npm@latest -g
RUN npm install
RUN yarn install
COPY . .
CMD ["yarn", "run", "build"]
